### PR TITLE
Add new animals

### PR DESCRIPTION
**Pull request by linagaggi**
Added a new animal

### CODE REVIEW

**Review by ChristoferBlomstedt — CHANGES_REQUESTED** [review]
Gruffalon is not an animal

**Review by linagaggi — COMMENTED** [review]
what's wrong?

**Review by ChristoferBlomstedt — COMMENTED** [review]
duh!

**Review by ChristoferBlomstedt — APPROVED** [review]

**Comment by ChristoferBlomstedt** [comment]
WHAT!!!

**Pull request merged**
